services:
  gazebo:
    build: .
    container_name: quadruped
    devices:
      - /dev/dri:/dev/dri
    environment:
      - LIBVA_DRIVER_NAME=iHD   # Set Intel GPU driver environment
      - DISPLAY=${DISPLAY}       # Set DISPLAY environment variable for X11
      - MPLBACKEND=Qt5Agg
    volumes:
      - /etc/OpenCL/vendors:/etc/OpenCL/vendors  # Mount OpenCL vendors
      - ${PWD}/src:/workspace/src  # Mount workspace source
      - /tmp/.X11-unix:/tmp/.X11-unix  # Mount X11 socket
    entrypoint: /bin/bash

    # Add the display entry for X11 forwarding to allow GUI apps from container
    network_mode: "host"